### ISSUE TITLE
List index out of range when calculating pp

### ISSUE THREAD

**Issue by zivoy** [The-CJ/oppadc.py#1]
calculating pp sometimes works and sometimes it breaks giving an IndexError

https://github.com/The-CJ/oppadc.py/blob/131b65855dae04965d937a260479d71be8045851/oppadc/osumap.py#L338

I'm suspecting that this line is the problem because when doing a breakpoint in my ide to stop when it breaks and evaluating this `len(self.timingpoints), (timing_index + 1)` I get `31, 31`

**Comment by The-CJ** [comment]
Can you give me a example map to test?

**Comment by zivoy** [comment]
https://osu.ppy.sh/beatmapsets/932901#osu/1971458
it failed on this map

**Comment by zivoy** [comment]
the issue is probably because indexing starts at 0 and len gives the total number of items in the list so the line should be
```python
if len(self.timingpoints) > (timing_index + 1):
```
