### ISSUE TITLE
getPP returns old result even if accuracy is changed.

### ISSUE THREAD

**Issue by RealistikDash** [The-CJ/oppadc.py#6]
While the title may not be very descriptive, I will try my best to describe the issue here.
I am attempting to calculate the PP for a beatmap at multiple accuracies. My current implementation for this currently looks like this:

```py
for acc in (100, 99, 98, 95):
    results.append(
        round(
            pp_map.getPP(mods, accuracy=acc).total_pp,
            2
        )
    )
```

As you can see, the `acc` variable is changed on every iteration. The issue is, all results of the PP calculations are equal to the result of the first accuracy, meaning the PP calculation fails to consider the change in accuracy.

Now I found a temporary solution, which is adding `recalculate=True` to the `getPP` function. However, it just doesn't feel right recalculating everything for a minor change (unless its absolutely required because of how PP works) and gives a significant performance penalty.

**Comment by The-CJ** [comment]
Sadly, it has to be. On the time i was writing this, i wondered myself if it is necessary, but yeah, that how the system works.
I even made some comments while writing it xD

https://github.com/The-CJ/oppadc.py/blob/master/oppadc/osumap.py#L400

Sorry to disappoint, you might want to blame ppy for this

**Comment by RealistikDash** [comment]
Oh fair enough, sorry for bothering
